version: '3.4'

services:
  webapp:
    image: webapp
    build:
      context: .
      dockerfile: Webapp/Dockerfile
    depends_on:
      - sql.data

  sql.data:
    image: microsoft/mssql-server-windows-developer